--
-- PostgreSQL database dump
--

\restrict UVoQ4MNhk4Lg5TP0FhtL9aQ5jwRcp0YqWjtDnpxueOi5LPAgGMWJXxLEHg8rPKf

-- Dumped from database version 15.18
-- Dumped by pg_dump version 15.18

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_cart; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_cart (
    id bigint NOT NULL,
    session_key character varying(255),
    created_at timestamp with time zone NOT NULL,
    user_id integer
);


ALTER TABLE public.core_cart OWNER TO postgres;

--
-- Name: core_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_cartitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT core_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.core_cartitem OWNER TO postgres;

--
-- Name: core_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.core_category OWNER TO postgres;

--
-- Name: core_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_coupon; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_coupon (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    discount_percent integer NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.core_coupon OWNER TO postgres;

--
-- Name: core_coupon_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_coupon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_coupon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_order (
    id bigint NOT NULL,
    full_name character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    address text NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    is_paid boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer,
    discount_amount numeric(10,2) NOT NULL,
    coupon_id bigint
);


ALTER TABLE public.core_order OWNER TO postgres;

--
-- Name: core_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_orderitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_orderitem (
    id bigint NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT core_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.core_orderitem OWNER TO postgres;

--
-- Name: core_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_product (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    sku character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    specifications jsonb NOT NULL,
    image_url character varying(1000) NOT NULL,
    image character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    brand character varying(100) NOT NULL
);


ALTER TABLE public.core_product OWNER TO postgres;

--
-- Name: core_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_review (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_review OWNER TO postgres;

--
-- Name: core_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_userprofile (
    id bigint NOT NULL,
    phone character varying(20) NOT NULL,
    address text NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    is_manager boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.core_userprofile OWNER TO postgres;

--
-- Name: core_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add cart	7	add_cart
26	Can change cart	7	change_cart
27	Can delete cart	7	delete_cart
28	Can view cart	7	view_cart
29	Can add category	8	add_category
30	Can change category	8	change_category
31	Can delete category	8	delete_category
32	Can view category	8	view_category
33	Can add order	9	add_order
34	Can change order	9	change_order
35	Can delete order	9	delete_order
36	Can view order	9	view_order
37	Can add user profile	10	add_userprofile
38	Can change user profile	10	change_userprofile
39	Can delete user profile	10	delete_userprofile
40	Can view user profile	10	view_userprofile
41	Can add product	11	add_product
42	Can change product	11	change_product
43	Can delete product	11	delete_product
44	Can view product	11	view_product
45	Can add order item	12	add_orderitem
46	Can change order item	12	change_orderitem
47	Can delete order item	12	delete_orderitem
48	Can view order item	12	view_orderitem
49	Can add cart item	13	add_cartitem
50	Can change cart item	13	change_cartitem
51	Can delete cart item	13	delete_cartitem
52	Can view cart item	13	view_cartitem
53	Can add coupon	14	add_coupon
54	Can change coupon	14	change_coupon
55	Can delete coupon	14	delete_coupon
56	Can view coupon	14	view_coupon
57	Can add review	15	add_review
58	Can change review	15	change_review
59	Can delete review	15	delete_review
60	Can view review	15	view_review
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$600000$DV1jl1eePl2Fzmla7rFrEF$KEQdmhd7R5RbskJ57B4forPr656+j7qIuQ9b5oTb+lk=	\N	f	customer	Sok	Dara	customer@gmail.com	f	t	2026-07-20 11:54:48.823193+00
1	pbkdf2_sha256$600000$1v2bZmTitefhnQjT92JD37$wRe0Kjymy0KWN2hiJvqxxdNbscXnqeaXsj/I681EQSA=	2026-07-23 16:26:52.701291+00	t	admin	Shop	Manager	admin@cyberstore.com	t	t	2026-07-20 11:54:48.612499+00
3	pbkdf2_sha256$600000$9T8jLLXAzs7S0IyTlkFDLk$GPsgZlJNUbXkAxxathZgRLHDj5lSGMG27jsVNjHRrH0=	2026-07-23 16:27:22.579389+00	f	povpisal			povpisal24@gmail.com	f	t	2026-07-20 12:05:58.149+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_cart; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_cart (id, session_key, created_at, user_id) FROM stdin;
1	nz2onwz8polowgpmvoa6mnpxxct79a6w	2026-07-20 11:58:42.772069+00	\N
2	\N	2026-07-20 12:03:38.000625+00	1
3	ssxfi2b5fqwtxa2p4ntv3xeyu14qq8zw	2026-07-20 12:04:13.695067+00	\N
4	\N	2026-07-20 12:05:58.431977+00	3
5	k5bmuzgetav3j52tgrcmycbi3yddedmh	2026-07-20 16:09:49.694492+00	\N
6	yuq7ozjfscj9hvl0fdquhu3tslqgmpzl	2026-07-21 11:03:00.359071+00	\N
8	c0fqud54hayry1ms8wojy17dx57odclx	2026-07-21 11:11:42.677788+00	\N
9	8h63ucy9fu30ncn1k4ap7xkl5v9s11rz	2026-07-21 11:12:15.77214+00	\N
10	ko4w065hjtgcj3v6ancxs02ia1jtdsy2	2026-07-21 11:12:31.244566+00	\N
41	cmi3p1zffdruyc6hc98z59fltmi6fpa6	2026-07-23 16:21:13.731545+00	\N
42	oqtmw1zootfzoy2ehblgzwlfrt1uyo5m	2026-07-23 16:26:32.103806+00	\N
43	d2mim11n5xq6bh6flaqp2vbnrsf7uof5	2026-07-23 16:27:15.090126+00	\N
\.


--
-- Data for Name: core_cartitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_cartitem (id, quantity, cart_id, product_id) FROM stdin;
\.


--
-- Data for Name: core_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_category (id, name, slug, description) FROM stdin;
32	CPUs	cpus	High-performance Central Processing Units.
33	GPUs	gpus	Graphics processing units for gaming & rendering.
34	RAM	ram	High-speed Random Access Memory modules.
35	Desktops	desktops	Custom pre-built desktop towers and workstations.
36	Laptops	laptops	Portable powerhouse laptops for gaming and productivity.
37	Monitors	monitors	High refresh gaming screens & UHD professional displays.
38	Accessories	accessories	Gaming and office peripherals like mice, keyboards, and headsets.
39	Storage	storage	Fast SSD storage drives and high-capacity HDDs.
\.


--
-- Data for Name: core_coupon; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_coupon (id, code, discount_percent, is_active) FROM stdin;
1	CYBERGPU	10	t
2	CYBER10	10	t
3	WELCOME15	15	t
\.


--
-- Data for Name: core_order; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_order (id, full_name, email, phone, address, city, country, total_amount, status, is_paid, created_at, updated_at, user_id, discount_amount, coupon_id) FROM stdin;
1	povpisal	povpisal24@gmail.com	061601604	# 229, st Lorm, Sangkat Phnom Penh Tmey, Khan SenSok, Phnom Penh, Cambodia	Phnom Penh	Cambodia	3499.00	Completed	t	2026-07-20 12:15:02.969118+00	2026-07-20 13:00:43.753675+00	3	0.00	\N
2	povpisal	povpisal24@gmail.com	01246789	# 229, st Lorm, Sangkat Phnom Penh Tmey, Khan SenSok, Phnom Penh, Cambodia	Phnom Penh	Cambodia	149.00	Completed	t	2026-07-21 11:03:49.031974+00	2026-07-21 11:05:11.344661+00	3	0.00	\N
\.


--
-- Data for Name: core_orderitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_orderitem (id, price, quantity, order_id, product_id) FROM stdin;
\.


--
-- Data for Name: core_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_product (id, name, slug, sku, description, price, stock, specifications, image_url, image, is_active, created_at, category_id, brand) FROM stdin;
114	AMD Ryzen 9 7900X CPU	amd-ryzen-9-7900x	CPU-AMD-R9-7900X	12 Cores and 24 processing threads based on the latest Zen 4 architecture. Reaches boost clocks up to 5.6 GHz.	429.00	15	{"TDP": "170W", "Cores": "12", "Socket": "Socket AM5", "Threads": "24", "Base Clock": "4.7 GHz"}	https://images.unsplash.com/photo-1591488320449-011701bb6704?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.817975+00	32	AMD
115	Intel Core i7-13700K CPU	intel-core-i7-13700k	CPU-INT-I7-13700K	13th Gen Intel Core processor featuring 16 cores (8 Performance cores & 8 Efficient cores). Incredible multitasking power.	369.00	2	{"TDP": "125W", "Cores": "16", "Socket": "LGA1700", "Threads": "24", "Base Clock": "3.4 GHz"}	https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.827392+00	32	Intel
116	AMD Ryzen 7 7800X3D CPU	amd-ryzen-7-7800x3d	CPU-AMD-R7-7800X3D	Designed specifically for gaming performance with AMD 3D V-Cache technology. 8 cores and 16 threads.	349.00	12	{"TDP": "120W", "Cores": "8", "Socket": "Socket AM5", "Threads": "16", "Base Clock": "4.2 GHz"}	https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.832197+00	32	AMD
117	Intel Core i9-14900K CPU	intel-core-i9-14900k	CPU-INT-I9-14900K	The ultimate 14th Gen Intel desktop processor. Boasts 24 cores (8P + 16E) reaching speeds up to 6.0 GHz.	529.00	6	{"TDP": "125W", "Cores": "24", "Socket": "LGA1700", "Threads": "32", "Max Clock": "6.0 GHz"}	https://images.unsplash.com/photo-1555680202-c86f0e12f086?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.839383+00	32	Intel
118	ASUS ROG Strix RTX 4080 GPU	asus-rog-strix-rtx-4080	GPU-ASUS-4080-STRIX	NVIDIA Ada Lovelace architecture graphics card. Features 16GB GDDR6X VRAM and high-efficiency axial fans.	1199.00	8	{"VRAM": "16GB GDDR6X", "Cores": "9728 CUDA", "Interface": "PCIe 4.0 x16", "Power Connectors": "1x 16-pin"}	https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.845066+00	33	ASUS
119	NVIDIA GeForce RTX 4070 Ti Super GPU	nvidia-rtx-4070-ti-super	GPU-NV-4070TI-SUPER	Packed with 16GB of fast GDDR6X memory and DLSS 3 frame generation capabilities.	799.00	9	{"VRAM": "16GB GDDR6X", "Ports": "1x HDMI, 3x DP", "Interface": "PCIe 4.0", "CUDA Cores": "8448"}	https://images.unsplash.com/photo-1588508065123-287b28e013da?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.849603+00	33	NVIDIA
120	AMD Radeon RX 7800 XT GPU	amd-radeon-rx-7800-xt	GPU-AMD-RX-7800XT	Engineered on the RDNA 3 chip architecture. Equips 16GB GDDR6 memory to master high-refresh 1440p gaming.	499.00	14	{"VRAM": "16GB GDDR6", "Ports": "1x HDMI, 3x DP", "Interface": "PCIe 4.0", "Processors": "3840 Stream"}	https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.854257+00	33	AMD
121	MSI RTX 4090 Suprim X GPU	msi-rtx-4090-suprim-x	GPU-MSI-4090-SUPRIMX	Ultimate luxury and power. 24GB of GDDR6X VRAM with custom TRI-FROZR 3S cooling system.	1999.00	3	{"TDP": "450W", "VRAM": "24GB GDDR6X", "Interface": "PCIe 4.0", "CUDA Cores": "16384"}	https://images.unsplash.com/photo-1591488320449-011701bb6704?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.860583+00	33	MSI
122	Corsair Vengeance 32GB DDR5 RAM	corsair-vengeance-32gb-ddr5	RAM-CSR-VG-32GB-D5	High-performance DDR5 memory optimized for modern motherboards. Frequency clock speed at 6000MHz.	125.00	25	{"Type": "DDR5", "Speed": "6000 MHz", "Latency": "CL36", "Capacity": "32GB (2x16GB)"}	https://images.unsplash.com/photo-1562976540-1502c2145186?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.865939+00	34	Corsair
123	G.Skill Trident Z5 Neo RGB 64GB RAM	gskill-trident-z5-64gb	RAM-GSK-TZ-64GB-D5	Ultra-fast 64GB DDR5 memory kit with custom programmable RGB lightbar and matte-black heatsinks.	219.00	10	{"Type": "DDR5", "Speed": "6000 MHz", "Latency": "CL30", "Capacity": "64GB (2x32GB)"}	https://images.unsplash.com/photo-1563770660941-20978e870e26?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.871895+00	34	G.Skill
124	Kingston FURY Beast 16GB DDR4 RAM	kingston-fury-beast-16gb-ddr4	RAM-KST-FB-16GB-D4	Cost-effective high-performance DDR4 memory upgrade. Auto-overclocking up to 3200MHz.	45.00	35	{"Type": "DDR4", "Speed": "3200 MHz", "Voltage": "1.35V", "Capacity": "16GB (2x8GB)"}	https://images.unsplash.com/photo-1541029071515-84cc54f84dc5?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.878088+00	34	Kingston
125	Teamgroup Delta RGB 32GB DDR5	teamgroup-delta-32gb-ddr5	RAM-TMG-DL-32GB-D5	120-degree ultra-wide angle RGB lighting DDR5 module, clocked at 6400MHz with custom cooling spreaders.	139.00	15	{"Type": "DDR5", "Speed": "6400 MHz", "Latency": "CL32", "Capacity": "32GB (2x16GB)"}	https://images.unsplash.com/photo-1563770660941-20978e870e26?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.88495+00	34	Teamgroup
126	MSI Aegis RS Gaming Desktop	msi-aegis-rs-desktop	DKT-MSI-AEGIS-RS	Built for high framerate gaming. Houses Intel Core i7 processor, RTX 4070 Ti, and 2TB NVMe SSD.	1899.00	4	{"OS": "Windows 11", "Memory": "32GB DDR5", "Storage": "2TB SSD", "Graphics": "RTX 4070 Ti", "Processor": "Intel i7-13700KF"}	https://images.unsplash.com/photo-1587831990711-23ca6441447b?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.89198+00	35	MSI
127	DELL Alienware Aurora R16 Desktop	dell-alienware-aurora-r16	DKT-DELL-AW-R16	Ultimate gaming performance desktop from Alienware. Liquid cooled i7 with RTX 4070 graphics.	1899.00	3	{"Memory": "32GB DDR5", "Storage": "1TB SSD", "Graphics": "RTX 4070 12GB", "Processor": "Intel i7-13700F"}	https://images.unsplash.com/photo-1618424181497-157f25b6ddd5?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.898418+00	35	DELL
128	Origin PC Millennium Workstation	origin-pc-millennium-workstation	DKT-ORIGIN-MILLENNIUM	A monolithic workspace powerhouse configured with a 24-Core AMD Threadripper CPU and dual RTX 4090 graphics cards.	4299.00	2	{"Memory": "128GB DDR5", "Storage": "4TB SSD", "Graphics": "2x RTX 4090 SLI", "Processor": "Threadripper 7960X"}	https://images.unsplash.com/photo-1547082299-de196ea013d6?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.904511+00	35	Origin PC
129	Apple Mac Studio M2 Max	apple-mac-studio-m2-max	DKT-APP-STUDIO-M2	Compact desktop workstation with massive processing bandwidth. Outfitted with Apple M2 Max chip.	1999.00	5	{"Storage": "512GB SSD", "Graphics": "30-Core GPU", "Processor": "Apple M2 Max (12-Core)", "Unified Memory": "32GB"}	https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.911439+00	35	Apple
130	ASUS ROG Zephyrus G14 Laptop	asus-rog-zephyrus-g14	LPT-ASUS-ROG-Z-G14	Compact and lightweight 14-inch gaming laptop. Features QHD+ 165Hz display and GeForce RTX 4060 graphics.	1499.00	5	{"Memory": "16GB", "Display": "14\\" QHD+ 165Hz", "Storage": "1TB SSD", "Graphics": "RTX 4060", "Processor": "AMD Ryzen 9 7940HS"}	https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.917305+00	36	ASUS
131	Lenovo Legion Pro 5i Laptop	lenovo-legion-pro-5i	LPT-LNV-LEGION-5I	Pro-grade gaming notebook with massive 16-inch high refresh display and GeForce RTX 4070 graphics.	1399.00	7	{"Memory": "32GB", "Display": "16\\" WQXGA 240Hz", "Storage": "1TB SSD", "Graphics": "RTX 4070", "Processor": "Intel i7-13700HX"}	https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.924162+00	36	Lenovo
132	Apple MacBook Pro 16" M3 Max Laptop	apple-macbook-pro-16-m3-max	LPT-APP-MBP16-M3MAX	Portable workstation built with the M3 Max custom chip. Runs demanding video pipelines and ML compilations.	3499.00	4	{"Memory": "48GB Unified", "Display": "16.2\\" Retina XDR 120Hz", "Storage": "1TB SSD", "Processor": "Apple M3 Max"}	https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.92979+00	36	Apple
133	DELL XPS 15 9530 Creator Laptop	dell-xps-15-9530	LPT-DELL-XPS-15	Premium thin-and-light laptop for creators. OLED touch display, Intel i9 CPU, and RTX 4060 GPU.	2299.00	6	{"Memory": "32GB", "Display": "15.6\\" OLED 3.5K Touch", "Storage": "1TB SSD", "Graphics": "RTX 4060", "Processor": "Intel i9-13900H"}	https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.93699+00	36	DELL
134	ASUS ROG Swift PG32UQX Monitor	asus-rog-swift-pg32uqx	MON-ASUS-PG32UQX	32-inch 4K HDR gaming monitor with Mini-LED backlighting, G-Sync Ultimate, and 144Hz refresh rate.	2499.00	4	{"Size": "32-inch", "Panel Type": "IPS Mini-LED", "Resolution": "4K UHD (3840x2160)", "Refresh Rate": "144Hz"}	https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.943927+00	37	ASUS
135	DELL UltraSharp U2723QE 4K Monitor	dell-ultrasharp-u2723qe	MON-DELL-U2723QE	27-inch 4K USB-C Hub monitor with IPS Black technology for double the contrast ratio and 98% DCI-P3 color.	579.00	12	{"Size": "27-inch", "Ports": "USB-C DP", "Panel Type": "IPS Black", "Resolution": "4K UHD", "Refresh Rate": "60Hz"}	https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.951387+00	37	DELL
136	LG UltraGear 27GP850-B Monitor	lg-ultragear-27gp850b	MON-LG-27GP850B	27-inch QHD Nano IPS gaming monitor with 1ms response time, 165Hz refresh rate (OC 180Hz), and G-Sync compatibility.	349.00	18	{"Size": "27-inch", "Resolution": "QHD (2560x1440)", "Refresh Rate": "180Hz (OC)", "Response Time": "1ms"}	https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.957573+00	37	LG
137	Samsung Odyssey G9 Curved Monitor	samsung-odyssey-g9	MON-SAM-G9-CURVED	49-inch super ultra-wide 1000R curved gaming monitor with Dual QHD resolution, 240Hz refresh, and 1ms response.	1299.00	3	{"Size": "49-inch Super Ultrawide", "Curvature": "1000R", "Resolution": "5120x1440", "Refresh Rate": "240Hz"}	https://images.unsplash.com/photo-1616763355548-1b606f439f86?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.964367+00	37	Samsung
138	Logitech G Pro X Superlight Mouse	logitech-g-pro-x-superlight	ACC-LOG-GPXS-MOUSE	Ultra-lightweight wireless gaming mouse designed for esports professionals. Weighs less than 63 grams.	129.00	30	{"Sensor": "HERO 25K", "Weight": "< 63g", "Battery Life": "70h", "Connectivity": "LIGHTSPEED Wireless"}	https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.970608+00	38	Logitech
139	Razer BlackWidow V4 Pro Keyboard	razer-blackwidow-v4-pro	ACC-RZR-BWV4-KB	Full-blown mechanical gaming keyboard with Razer Green clicky switches, underglow RGB, and dedicated macro keys.	229.00	15	{"RGB": "Chroma Per-key", "Layout": "Full Size", "Macros": "8 Dedicated", "Switches": "Razer Green Mechanical"}	https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.976119+00	38	Razer
140	Corsair HS80 RGB Wireless Headset	corsair-hs80-rgb-wireless	ACC-CSR-HS80-HEADSET	Premium gaming headset with SLIPSTREAM wireless audio, broadcast-grade omnidirectional microphone, and Dolby Atmos support.	149.00	20	{"Audio": "Dolby Atmos Spatial", "Driver": "50mm Neodymium", "Wireless": "SLIPSTREAM", "Frequency": "20Hz-40kHz"}	https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.98084+00	38	Corsair
141	Logitech MX Master 3S Mouse	logitech-mx-master-3s	ACC-LOG-MX3S-MOUSE	Ergonomic office productivity mouse with MagSpeed electromagnetic scrolling and quiet click switches.	99.00	40	{"Sensor": "8K DPI Darkfield", "Battery": "70 days", "Buttons": "7 Programmable", "Scrolling": "MagSpeed Metal Wheel"}	https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.985518+00	38	Logitech
142	Samsung 990 PRO 2TB NVMe SSD	samsung-990-pro-2tb	STG-SAM-990P-2TB	PCIe Gen4 solid state drive delivering peak sequential read speeds up to 7450 MB/s for PC hardware enthusiasts.	179.00	25	{"Capacity": "2TB", "Interface": "PCIe Gen4.0 x4 NVMe", "Read Speed": "Up to 7450 MB/s", "Write Speed": "Up to 6900 MB/s"}	https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.990151+00	39	Samsung
143	Crucial T700 1TB PCIe 5.0 SSD	crucial-t700-1tb-pcie5	STG-CRL-T700-1TB	Next-gen PCIe 5.0 NVMe SSD boasting record speeds up to 12400 MB/s. Prepared for DirectStorage configurations.	169.00	8	{"Capacity": "1TB", "Interface": "PCIe Gen5.0 x4 NVMe", "Read Speed": "Up to 11700 MB/s", "Write Speed": "Up to 9500 MB/s"}	https://images.unsplash.com/photo-1597852074816-d933c7d2b988?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:01.994878+00	39	Crucial
144	WD Black SN850X 2TB NVMe SSD	wd-black-sn850x-2tb	STG-WDB-SN850X-2TB	Premium high-speed gaming SSD with optional heatsink. Delivers read speeds up to 7300 MB/s.	159.00	18	{"Capacity": "2TB", "Interface": "PCIe Gen4 x4", "Read Speed": "7300 MB/s", "Form Factor": "M.2 2280"}	https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:02.001312+00	39	WD
145	Samsung T7 Shield 2TB Portable SSD	samsung-t7-shield-2tb	STG-SAM-T7S-2TB	Super durable portable solid state drive with IP65 water/dust resistance and 1050 MB/s transfer speeds.	149.00	22	{"Capacity": "2TB", "Interface": "USB 3.2 Gen2", "Protection": "IP65 Rated", "Read Speed": "1050 MB/s"}	https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=300&auto=format&fit=crop		t	2026-07-23 17:10:02.008048+00	39	Samsung
\.


--
-- Data for Name: core_review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_review (id, rating, comment, created_at, product_id, user_id) FROM stdin;
5	5	Best gaming CPU on the market! Low TDP and insane performance.	2026-07-23 17:10:02.032817+00	116	2
6	5	Highly recommended. Runs cool and delivers top-tier 1% low framerates.	2026-07-23 17:10:02.038173+00	116	1
7	5	Absolute monster of a card! A bit expensive but completely worth the rendering speeds.	2026-07-23 17:10:02.046932+00	121	2
8	4	Super clean desktop. Quiet cooling. Wish it had a bit more expansion slots.	2026-07-23 17:10:02.053708+00	127	2
\.


--
-- Data for Name: core_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_userprofile (id, phone, address, city, country, is_manager, user_id) FROM stdin;
2	+855 98 765 432	St 271, Sangkat Boeung Salang	Phnom Penh	Cambodia	f	2
3			Phnom Penh	Cambodia	f	3
1	+855 12 345 678	Russian Federation Blvd (110), SETEC	Phnom Penh	Cambodia	t	1
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	cart
8	core	category
9	core	order
10	core	userprofile
11	core	product
12	core	orderitem
13	core	cartitem
14	core	coupon
15	core	review
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-20 11:54:33.054901+00
2	auth	0001_initial	2026-07-20 11:54:33.272394+00
3	admin	0001_initial	2026-07-20 11:54:33.325266+00
4	admin	0002_logentry_remove_auto_add	2026-07-20 11:54:33.335634+00
5	admin	0003_logentry_add_action_flag_choices	2026-07-20 11:54:33.345674+00
6	contenttypes	0002_remove_content_type_name	2026-07-20 11:54:33.362618+00
7	auth	0002_alter_permission_name_max_length	2026-07-20 11:54:33.375184+00
8	auth	0003_alter_user_email_max_length	2026-07-20 11:54:33.398853+00
9	auth	0004_alter_user_username_opts	2026-07-20 11:54:33.411233+00
10	auth	0005_alter_user_last_login_null	2026-07-20 11:54:33.424297+00
11	auth	0006_require_contenttypes_0002	2026-07-20 11:54:33.43187+00
12	auth	0007_alter_validators_add_error_messages	2026-07-20 11:54:33.441683+00
13	auth	0008_alter_user_username_max_length	2026-07-20 11:54:33.467199+00
14	auth	0009_alter_user_last_name_max_length	2026-07-20 11:54:33.477594+00
15	auth	0010_alter_group_name_max_length	2026-07-20 11:54:33.493007+00
16	auth	0011_update_proxy_permissions	2026-07-20 11:54:33.503451+00
17	auth	0012_alter_user_first_name_max_length	2026-07-20 11:54:33.51332+00
18	core	0001_initial	2026-07-20 11:54:33.799576+00
19	sessions	0001_initial	2026-07-20 11:54:33.83907+00
20	core	0002_product_brand	2026-07-20 12:21:55.209743+00
21	core	0003_coupon_order_discount_amount_order_coupon_review	2026-07-23 16:15:10.721353+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
po6nqssxfptyzh7sjo8s1ddd9n07bksg	.eJxVjDsOwjAQRO_iGllex79Q0ucM0Xq9xgFkS_lUiLuTSClA0817M28x4raWcVt4HqckrgLE5beLSE-uB0gPrPcmqdV1nqI8FHnSRQ4t8et2un8HBZeyr73xpCx1QBmQjNUu6KCgdx6JI4WAmV2wxmnwe5yOHKCPZBRbB7kTny_IwzcU:1wlnLQ:hU0VncLF9mPeH6f1ou3xIL9m_UXg8I61DlqgygGbcGg	2026-08-03 12:43:40.142427+00
0zrrjo8pidvprl239m66x66wqy52djkw	.eJxVjEEOwiAQRe_C2hCmgFCX7nsGwsyAVA0kpV0Z765NutDtf-_9lwhxW0vYelrCzOIitDj9bhjpkeoO-B7rrUlqdV1mlLsiD9rl1Dg9r4f7d1BiL98atdaGlCWPYx4tMbIjZp-9S5SHjB6UYYYzJIjK6GzUgJABjEOrMYr3BwVCOH4:1wm8Ow:W38DCkUYP2iik9jbPpzQFMnCgaoVatPgZBu_L6eoBG4	2026-08-04 11:12:42.79447+00
nrz6oq48fu0o67ruha4aoilles6c737d	.eJxVjEEOwiAQRe_C2hCmgFCX7nsGwsyAVA0kpV0Z765NutDtf-_9lwhxW0vYelrCzOIitDj9bhjpkeoO-B7rrUlqdV1mlLsiD9rl1Dg9r4f7d1BiL98atdaGlCWPYx4tMbIjZp-9S5SHjB6UYYYzJIjK6GzUgJABjEOrMYr3BwVCOH4:1wmwGY:Nw3H79PAKc0vTfqV2EwParasc47Zgctp_Cwo9Hd5vls	2026-08-06 16:27:22.588594+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_cart_id_seq', 43, true);


--
-- Name: core_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_cartitem_id_seq', 5, true);


--
-- Name: core_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_category_id_seq', 39, true);


--
-- Name: core_coupon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_coupon_id_seq', 3, true);


--
-- Name: core_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_order_id_seq', 2, true);


--
-- Name: core_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_orderitem_id_seq', 2, true);


--
-- Name: core_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_product_id_seq', 145, true);


--
-- Name: core_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_review_id_seq', 8, true);


--
-- Name: core_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_userprofile_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 21, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_cart core_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_cart
    ADD CONSTRAINT core_cart_pkey PRIMARY KEY (id);


--
-- Name: core_cartitem core_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_cartitem
    ADD CONSTRAINT core_cartitem_pkey PRIMARY KEY (id);


--
-- Name: core_category core_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_category
    ADD CONSTRAINT core_category_name_key UNIQUE (name);


--
-- Name: core_category core_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_category
    ADD CONSTRAINT core_category_pkey PRIMARY KEY (id);


--
-- Name: core_category core_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_category
    ADD CONSTRAINT core_category_slug_key UNIQUE (slug);


--
-- Name: core_coupon core_coupon_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_coupon
    ADD CONSTRAINT core_coupon_code_key UNIQUE (code);


--
-- Name: core_coupon core_coupon_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_coupon
    ADD CONSTRAINT core_coupon_pkey PRIMARY KEY (id);


--
-- Name: core_order core_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_order
    ADD CONSTRAINT core_order_pkey PRIMARY KEY (id);


--
-- Name: core_orderitem core_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_orderitem
    ADD CONSTRAINT core_orderitem_pkey PRIMARY KEY (id);


--
-- Name: core_product core_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_product
    ADD CONSTRAINT core_product_pkey PRIMARY KEY (id);


--
-- Name: core_product core_product_sku_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_product
    ADD CONSTRAINT core_product_sku_key UNIQUE (sku);


--
-- Name: core_product core_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_product
    ADD CONSTRAINT core_product_slug_key UNIQUE (slug);


--
-- Name: core_review core_review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_review
    ADD CONSTRAINT core_review_pkey PRIMARY KEY (id);


--
-- Name: core_review core_review_product_id_user_id_8f834a72_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_review
    ADD CONSTRAINT core_review_product_id_user_id_8f834a72_uniq UNIQUE (product_id, user_id);


--
-- Name: core_userprofile core_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_pkey PRIMARY KEY (id);


--
-- Name: core_userprofile core_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_cart_session_key_01902993; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_cart_session_key_01902993 ON public.core_cart USING btree (session_key);


--
-- Name: core_cart_session_key_01902993_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_cart_session_key_01902993_like ON public.core_cart USING btree (session_key varchar_pattern_ops);


--
-- Name: core_cart_user_id_2ebeb843; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_cart_user_id_2ebeb843 ON public.core_cart USING btree (user_id);


--
-- Name: core_cartitem_cart_id_5256d769; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_cartitem_cart_id_5256d769 ON public.core_cartitem USING btree (cart_id);


--
-- Name: core_cartitem_product_id_2640c4a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_cartitem_product_id_2640c4a2 ON public.core_cartitem USING btree (product_id);


--
-- Name: core_category_name_55b68161_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_category_name_55b68161_like ON public.core_category USING btree (name varchar_pattern_ops);


--
-- Name: core_category_slug_384eca9c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_category_slug_384eca9c_like ON public.core_category USING btree (slug varchar_pattern_ops);


--
-- Name: core_coupon_code_f623b39c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_coupon_code_f623b39c_like ON public.core_coupon USING btree (code varchar_pattern_ops);


--
-- Name: core_order_coupon_id_bade53ba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_order_coupon_id_bade53ba ON public.core_order USING btree (coupon_id);


--
-- Name: core_order_user_id_b03bbffd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_order_user_id_b03bbffd ON public.core_order USING btree (user_id);


--
-- Name: core_orderitem_order_id_30929c10; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_orderitem_order_id_30929c10 ON public.core_orderitem USING btree (order_id);


--
-- Name: core_orderitem_product_id_0c2047cd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_orderitem_product_id_0c2047cd ON public.core_orderitem USING btree (product_id);


--
-- Name: core_product_category_id_b9d8ff9f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_product_category_id_b9d8ff9f ON public.core_product USING btree (category_id);


--
-- Name: core_product_sku_6168965a_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_product_sku_6168965a_like ON public.core_product USING btree (sku varchar_pattern_ops);


--
-- Name: core_product_slug_8cf0d080_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_product_slug_8cf0d080_like ON public.core_product USING btree (slug varchar_pattern_ops);


--
-- Name: core_review_product_id_27ba91fa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_review_product_id_27ba91fa ON public.core_review USING btree (product_id);


--
-- Name: core_review_user_id_b6106194; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_review_user_id_b6106194 ON public.core_review USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cart core_cart_user_id_2ebeb843_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_cart
    ADD CONSTRAINT core_cart_user_id_2ebeb843_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cartitem core_cartitem_cart_id_5256d769_fk_core_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_cartitem
    ADD CONSTRAINT core_cartitem_cart_id_5256d769_fk_core_cart_id FOREIGN KEY (cart_id) REFERENCES public.core_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cartitem core_cartitem_product_id_2640c4a2_fk_core_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_cartitem
    ADD CONSTRAINT core_cartitem_product_id_2640c4a2_fk_core_product_id FOREIGN KEY (product_id) REFERENCES public.core_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_order core_order_coupon_id_bade53ba_fk_core_coupon_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_order
    ADD CONSTRAINT core_order_coupon_id_bade53ba_fk_core_coupon_id FOREIGN KEY (coupon_id) REFERENCES public.core_coupon(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_order core_order_user_id_b03bbffd_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_order
    ADD CONSTRAINT core_order_user_id_b03bbffd_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_orderitem core_orderitem_order_id_30929c10_fk_core_order_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_orderitem
    ADD CONSTRAINT core_orderitem_order_id_30929c10_fk_core_order_id FOREIGN KEY (order_id) REFERENCES public.core_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_orderitem core_orderitem_product_id_0c2047cd_fk_core_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_orderitem
    ADD CONSTRAINT core_orderitem_product_id_0c2047cd_fk_core_product_id FOREIGN KEY (product_id) REFERENCES public.core_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_product core_product_category_id_b9d8ff9f_fk_core_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_product
    ADD CONSTRAINT core_product_category_id_b9d8ff9f_fk_core_category_id FOREIGN KEY (category_id) REFERENCES public.core_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_review core_review_product_id_27ba91fa_fk_core_product_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_review
    ADD CONSTRAINT core_review_product_id_27ba91fa_fk_core_product_id FOREIGN KEY (product_id) REFERENCES public.core_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_review core_review_user_id_b6106194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_review
    ADD CONSTRAINT core_review_user_id_b6106194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_userprofile core_userprofile_user_id_5141ad90_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_userprofile
    ADD CONSTRAINT core_userprofile_user_id_5141ad90_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict UVoQ4MNhk4Lg5TP0FhtL9aQ5jwRcp0YqWjtDnpxueOi5LPAgGMWJXxLEHg8rPKf

