# Generated by Django 4.2.30 on 2026-07-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='e.g. Apple, Lenovo, Dell, ASUS, Intel, AMD, Corsair', max_length=100),
        ),
    ]
