# Generated by Django 4.2.30 on 2026-08-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coupon_order_discount_amount_order_coupon_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'System Admin'), ('sale', 'Sale Staff'), ('it', 'IT Support')], default='customer', max_length=20),
        ),
    ]
